tagline: Software engineer. Alchemist.
# host: igas.me
markdown: kramdown
title: Igas
url: http://igas.me
collections:
  talks:
    output: true
    permalink: /talks/:path/
tools:
  ga: UA-50593886-1
  google-site-verification: mZn8S0xI9gUi2vt1149e6DIZJSa6w3XfLEOyBMQH03U
owner:
  name: Igor Kapkov
  avatar: http://gravatar.com/avatar/4deabcd4e46af59a4954674673143235?s=208
  email: igasgeek@me.com
  facebook: igasgeek
  github: igas
  goodreads: igas
  instagram: igasgeek
  linkedin: ikapkov
  stackoverflow: 861648
  twitter: igasgeek
